// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Quo.OpenApiClient.V1.CallSummaries.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.CallSummaries
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\call-summaries
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CallSummariesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Quo.OpenApiClient.v1.callSummaries.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallSummaries.Item.WithCallItemRequestBuilder"/></returns>
        public global::Soenneker.Quo.OpenApiClient.V1.CallSummaries.Item.WithCallItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("callId", position);
                return new global::Soenneker.Quo.OpenApiClient.V1.CallSummaries.Item.WithCallItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallSummaries.CallSummariesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CallSummariesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/call-summaries", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallSummaries.CallSummariesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CallSummariesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/call-summaries", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
