// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithCallGetResponse_data : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The duration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration? Duration { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration Duration { get; set; }
#endif
        /// <summary>The unique identifier of the call voicemail.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The recordingUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_recordingUrl? RecordingUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_recordingUrl RecordingUrl { get; set; }
#endif
        /// <summary>The current status of the call voicemail.</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_status? Status { get; set; }
        /// <summary>The transcript property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_transcript? Transcript { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_transcript Transcript { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "duration", n => { Duration = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration>(global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "recordingUrl", n => { RecordingUrl = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_recordingUrl>(global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_recordingUrl.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_status>(); } },
                { "transcript", n => { Transcript = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_transcript>(global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_transcript.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration>("duration", Duration);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_recordingUrl>("recordingUrl", RecordingUrl);
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_transcript>("transcript", Transcript);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_durationMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCallGetResponse_data_duration : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_durationMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_durationMember1? WithCallGetResponseDataDurationMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_durationMember1 WithCallGetResponseDataDurationMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.WithCallGetResponseDataDurationMember1 = new global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_durationMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithCallGetResponseDataDurationMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WithCallGetResponseDataDurationMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_durationMember1>(null, WithCallGetResponseDataDurationMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_recordingUrlMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCallGetResponse_data_recordingUrl : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_recordingUrlMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_recordingUrlMember1? WithCallGetResponseDataRecordingUrlMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_recordingUrlMember1 WithCallGetResponseDataRecordingUrlMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_recordingUrl"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_recordingUrl CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_recordingUrl();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WithCallGetResponseDataRecordingUrlMember1 = new global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_recordingUrlMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithCallGetResponseDataRecordingUrlMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WithCallGetResponseDataRecordingUrlMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_recordingUrlMember1>(null, WithCallGetResponseDataRecordingUrlMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_transcriptMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCallGetResponse_data_transcript : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_transcriptMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_transcriptMember1? WithCallGetResponseDataTranscriptMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_transcriptMember1 WithCallGetResponseDataTranscriptMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_transcript"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_transcript CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data.WithCallGetResponse_data_transcript();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WithCallGetResponseDataTranscriptMember1 = new global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_transcriptMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithCallGetResponseDataTranscriptMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WithCallGetResponseDataTranscriptMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.Item.WithCallGetResponse_data_transcriptMember1>(null, WithCallGetResponseDataTranscriptMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
