// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Webhooks.CallSummaries
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CallSummariesPostResponse_data_events
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "call.summary.completed")]
        #pragma warning disable CS1591
        CallSummaryCompleted,
        #pragma warning restore CS1591
    }
}
