// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Quo.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Messages.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\messages\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessagesItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagesItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/messages/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagesItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/messages/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Get a message by its unique identifier.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1402">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1500">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1200?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1200> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1401.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1402.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1404.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1500.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1200>(requestInfo, global::Soenneker.Quo.OpenApiClient.Models.GetMessageByIdV1200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a message by its unique identifier.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
