// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Messages.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MessagesGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The timestamp when the message was created at, in ISO 8601 format</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The direction of the message relative to the OpenPhone number.</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_direction? Direction { get; set; }
        /// <summary>A phone number in E.164 format, including the country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>The unique identifier of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The phoneNumberId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data.MessagesGetResponse_data_phoneNumberId? PhoneNumberId { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data.MessagesGetResponse_data_phoneNumberId PhoneNumberId { get; set; }
#endif
        /// <summary>The status of the message.</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_status? Status { get; set; }
        /// <summary>The content of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? To { get; set; }
#nullable restore
#else
        public List<string> To { get; set; }
#endif
        /// <summary>The timestamp when the message status was last updated, in ISO 8601 format.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The unique identifier of the user who sent the message. Null for incoming messages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data"/> and sets the default values.
        /// </summary>
        public MessagesGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "direction", n => { Direction = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_direction>(); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "phoneNumberId", n => { PhoneNumberId = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data.MessagesGetResponse_data_phoneNumberId>(global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data.MessagesGetResponse_data_phoneNumberId.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_status>(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "to", n => { To = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_direction>("direction", Direction);
            writer.WriteStringValue("from", From);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data.MessagesGetResponse_data_phoneNumberId>("phoneNumberId", PhoneNumberId);
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_status>("status", Status);
            writer.WriteStringValue("text", Text);
            writer.WriteCollectionOfPrimitiveValues<string>("to", To);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_phoneNumberIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MessagesGetResponse_data_phoneNumberId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_phoneNumberIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_phoneNumberIdMember1? MessagesGetResponseDataPhoneNumberIdMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_phoneNumberIdMember1 MessagesGetResponseDataPhoneNumberIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data.MessagesGetResponse_data_phoneNumberId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data.MessagesGetResponse_data_phoneNumberId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data.MessagesGetResponse_data_phoneNumberId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.MessagesGetResponseDataPhoneNumberIdMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_phoneNumberIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MessagesGetResponseDataPhoneNumberIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MessagesGetResponseDataPhoneNumberIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Messages.Item.MessagesGetResponse_data_phoneNumberIdMember1>(null, MessagesGetResponseDataPhoneNumberIdMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
