// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CallTranscriptsGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier of the call to which this transcript belongs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallId { get; set; }
#nullable restore
#else
        public string CallId { get; set; }
#endif
        /// <summary>The timestamp when the transcription was created, in ISO 8601 format.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The dialogue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data.CallTranscriptsGetResponse_data_dialogue? Dialogue { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data.CallTranscriptsGetResponse_data_dialogue Dialogue { get; set; }
#endif
        /// <summary>The total duration of the transcribed call in seconds.</summary>
        public double? Duration { get; set; }
        /// <summary>The status of the call transcription.</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data"/> and sets the default values.
        /// </summary>
        public CallTranscriptsGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "callId", n => { CallId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "dialogue", n => { Dialogue = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data.CallTranscriptsGetResponse_data_dialogue>(global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data.CallTranscriptsGetResponse_data_dialogue.CreateFromDiscriminatorValue); } },
                { "duration", n => { Duration = n.GetDoubleValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("callId", CallId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data.CallTranscriptsGetResponse_data_dialogue>("dialogue", Dialogue);
            writer.WriteDoubleValue("duration", Duration);
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember2"/>, List&lt;global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember1&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CallTranscriptsGetResponse_data_dialogue : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember1&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember1>? CallTranscriptsGetResponseDataDialogueMember1 { get; set; }
#nullable restore
#else
            public List<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember1> CallTranscriptsGetResponseDataDialogueMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember2? CallTranscriptsGetResponseDataDialogueMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember2 CallTranscriptsGetResponseDataDialogueMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data.CallTranscriptsGetResponse_data_dialogue"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data.CallTranscriptsGetResponse_data_dialogue CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data.CallTranscriptsGetResponse_data_dialogue();
                if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember1>(global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember1.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember1> callTranscriptsGetResponseDataDialogueMember1Value)
                {
                    result.CallTranscriptsGetResponseDataDialogueMember1 = callTranscriptsGetResponseDataDialogueMember1Value;
                }
                else {
                    result.CallTranscriptsGetResponseDataDialogueMember2 = new global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CallTranscriptsGetResponseDataDialogueMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CallTranscriptsGetResponseDataDialogueMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CallTranscriptsGetResponseDataDialogueMember1 != null)
                {
                    writer.WriteCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember1>(null, CallTranscriptsGetResponseDataDialogueMember1);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsGetResponse_data_dialogueMember2>(null, CallTranscriptsGetResponseDataDialogueMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
