// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithCallGetResponse_data : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The duration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration? Duration { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration Duration { get; set; }
#endif
        /// <summary>The unique identifier of the call recording.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The startTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_startTime? StartTime { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_startTime StartTime { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_status? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_status Status { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_type? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_type Type { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_url? Url { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_url Url { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "duration", n => { Duration = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration>(global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "startTime", n => { StartTime = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_startTime>(global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_startTime.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_status>(global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_status.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_type>(global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_type.CreateFromDiscriminatorValue); } },
                { "url", n => { Url = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_url>(global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_url.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration>("duration", Duration);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_startTime>("startTime", StartTime);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_type>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_url>("url", Url);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_durationMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCallGetResponse_data_duration : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_durationMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_durationMember1? WithCallGetResponseDataDurationMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_durationMember1 WithCallGetResponseDataDurationMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_duration();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.WithCallGetResponseDataDurationMember1 = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_durationMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithCallGetResponseDataDurationMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WithCallGetResponseDataDurationMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_durationMember1>(null, WithCallGetResponseDataDurationMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_startTimeMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCallGetResponse_data_startTime : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_startTimeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_startTimeMember1? WithCallGetResponseDataStartTimeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_startTimeMember1 WithCallGetResponseDataStartTimeMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_startTime"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_startTime CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_startTime();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.WithCallGetResponseDataStartTimeMember1 = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_startTimeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithCallGetResponseDataStartTimeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WithCallGetResponseDataStartTimeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_startTimeMember1>(null, WithCallGetResponseDataStartTimeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_statusMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCallGetResponse_data_status : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_statusMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_statusMember1? WithCallGetResponseDataStatusMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_statusMember1 WithCallGetResponseDataStatusMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_status"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_status CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_status();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WithCallGetResponseDataStatusMember1 = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_statusMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithCallGetResponseDataStatusMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WithCallGetResponseDataStatusMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_statusMember1>(null, WithCallGetResponseDataStatusMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_typeMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCallGetResponse_data_type : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_typeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_typeMember1? WithCallGetResponseDataTypeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_typeMember1 WithCallGetResponseDataTypeMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_type"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_type CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_type();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WithCallGetResponseDataTypeMember1 = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_typeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithCallGetResponseDataTypeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WithCallGetResponseDataTypeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_typeMember1>(null, WithCallGetResponseDataTypeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_urlMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCallGetResponse_data_url : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_urlMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_urlMember1? WithCallGetResponseDataUrlMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_urlMember1 WithCallGetResponseDataUrlMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_url"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_url CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data.WithCallGetResponse_data_url();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WithCallGetResponseDataUrlMember1 = new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_urlMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithCallGetResponseDataUrlMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WithCallGetResponseDataUrlMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.Item.WithCallGetResponse_data_urlMember1>(null, WithCallGetResponseDataUrlMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
