// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithPhoneNumberGetResponse_data_restrictions_calling : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The phone-number usage restriction status for a specific region</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling_CA? CA { get; set; }
        /// <summary>The phone-number usage restriction status for a specific region</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling_Intl? Intl { get; set; }
        /// <summary>The phone-number usage restriction status for a specific region</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling_US? US { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling"/> and sets the default values.
        /// </summary>
        public WithPhoneNumberGetResponse_data_restrictions_calling()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CA", n => { CA = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling_CA>(); } },
                { "Intl", n => { Intl = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling_Intl>(); } },
                { "US", n => { US = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling_US>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling_CA>("CA", CA);
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling_Intl>("Intl", Intl);
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.Item.WithPhoneNumberGetResponse_data_restrictions_calling_US>("US", US);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
