// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Webhooks.Messages
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MessagesPostRequestBody_events
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "message.received")]
        #pragma warning disable CS1591
        MessageReceived,
        #pragma warning restore CS1591
        [EnumMember(Value = "message.delivered")]
        #pragma warning disable CS1591
        MessageDelivered,
        #pragma warning restore CS1591
    }
}
