// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Conversations
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\conversations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConversationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConversationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/conversations?maxResults={maxResults}{&createdAfter*,createdBefore*,excludeInactive*,pageToken*,phoneNumber*,phoneNumbers*,updatedAfter*,updatedBefore*,userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConversationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/conversations?maxResults={maxResults}{&createdAfter*,createdBefore*,excludeInactive*,pageToken*,phoneNumber*,phoneNumbers*,updatedAfter*,updatedBefore*,userId*}", rawUrl)
        {
        }
        /// <summary>
        /// Fetch a paginated list of conversations of OpenPhone conversations. Can be filtered by user and/or phone numbers. Defaults to all conversations in the OpenPhone organization. Results are returned in descending order based on the most recent conversation.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder.ConversationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder.ConversationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Quo.OpenApiClient.V1.Conversations.Conversations500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsGetResponse>(requestInfo, global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch a paginated list of conversations of OpenPhone conversations. Can be filtered by user and/or phone numbers. Defaults to all conversations in the OpenPhone organization. Results are returned in descending order based on the most recent conversation.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder.ConversationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder.ConversationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Fetch a paginated list of conversations of OpenPhone conversations. Can be filtered by user and/or phone numbers. Defaults to all conversations in the OpenPhone organization. Results are returned in descending order based on the most recent conversation.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConversationsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("createdAfter")]
            public DateTimeOffset? CreatedAfter { get; set; }
            [QueryParameter("createdBefore")]
            public DateTimeOffset? CreatedBefore { get; set; }
            [QueryParameter("excludeInactive")]
            public bool? ExcludeInactive { get; set; }
            [QueryParameter("maxResults")]
            public int? MaxResults { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pageToken")]
            public string? PageToken { get; set; }
#nullable restore
#else
            [QueryParameter("pageToken")]
            public string PageToken { get; set; }
#endif
            [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("phoneNumber")]
            public string? PhoneNumber { get; set; }
#nullable restore
#else
            [QueryParameter("phoneNumber")]
            public string PhoneNumber { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("phoneNumbers")]
            public string[]? PhoneNumbers { get; set; }
#nullable restore
#else
            [QueryParameter("phoneNumbers")]
            public string[] PhoneNumbers { get; set; }
#endif
            [QueryParameter("updatedAfter")]
            public DateTimeOffset? UpdatedAfter { get; set; }
            [QueryParameter("updatedBefore")]
            public DateTimeOffset? UpdatedBefore { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("userId")]
            public string? UserId { get; set; }
#nullable restore
#else
            [QueryParameter("userId")]
            public string UserId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
