// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.CallTranscripts
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\call-transcripts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CallTranscriptsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Quo.OpenApiClient.v1.callTranscripts.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsItemRequestBuilder"/></returns>
        public global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.Item.CallTranscriptsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.CallTranscriptsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CallTranscriptsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/call-transcripts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.CallTranscriptsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CallTranscriptsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/call-transcripts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
