// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CallTranscriptsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The events property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody_events?>? Events { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody_events?> Events { get; set; }
#endif
        /// <summary>The webhook&apos;s label.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The resourceIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody.CallTranscriptsPostRequestBody_resourceIds? ResourceIds { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody.CallTranscriptsPostRequestBody_resourceIds ResourceIds { get; set; }
#endif
        /// <summary>The status of the webhook.</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody_status? Status { get; set; }
        /// <summary>The endpoint that receives events from the webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The ID of the user that creates the webhook. If not provided, default to workspace owner.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody"/> and sets the default values.
        /// </summary>
        public CallTranscriptsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "events", n => { Events = n.GetCollectionOfEnumValues<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody_events>()?.AsList(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "resourceIds", n => { ResourceIds = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody.CallTranscriptsPostRequestBody_resourceIds>(global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody.CallTranscriptsPostRequestBody_resourceIds.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody_status>(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody_events>("events", Events);
            writer.WriteStringValue("label", Label);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody.CallTranscriptsPostRequestBody_resourceIds>("resourceIds", ResourceIds);
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody_status>("status", Status);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CallTranscriptsPostRequestBody_resourceIds : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody.CallTranscriptsPostRequestBody_resourceIds"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody.CallTranscriptsPostRequestBody_resourceIds CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Webhooks.CallTranscripts.CallTranscriptsPostRequestBody.CallTranscriptsPostRequestBody_resourceIds();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
