// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Quo.OpenApiClient.V1.Conversations.Item.MarkAsRead;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Conversations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\conversations\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConversationsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The markAsRead property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Conversations.Item.MarkAsRead.MarkAsReadRequestBuilder MarkAsRead
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.Conversations.Item.MarkAsRead.MarkAsReadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.Item.ConversationsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConversationsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/conversations/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Conversations.Item.ConversationsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConversationsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/conversations/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
