// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.ContactCustomFields
{
    /// <summary>The data type of the custom contact field, determining what kind of information can be stored and how it should be formatted.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ContactCustomFieldsGetResponse_data_type
    {
        [EnumMember(Value = "address")]
        #pragma warning disable CS1591
        Address,
        #pragma warning restore CS1591
        [EnumMember(Value = "boolean")]
        #pragma warning disable CS1591
        Boolean,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi-select")]
        #pragma warning disable CS1591
        MultiSelect,
        #pragma warning restore CS1591
        [EnumMember(Value = "number")]
        #pragma warning disable CS1591
        Number,
        #pragma warning restore CS1591
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        String,
        #pragma warning restore CS1591
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
    }
}
