// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Webhooks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebhooksGetResponse_dataMember1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date the webhook was created at, in ISO_8601 format.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The deletedAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_deletedAt? DeletedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_deletedAt DeletedAt { get; set; }
#endif
        /// <summary>The events property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_events?>? Events { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_events?> Events { get; set; }
#endif
        /// <summary>The webhook&apos;s ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Webhook key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_label? Label { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_label Label { get; set; }
#endif
        /// <summary>The unique identifier of the organization the webhook belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgId { get; set; }
#nullable restore
#else
        public string OrgId { get; set; }
#endif
        /// <summary>The resourceIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_resourceIds? ResourceIds { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_resourceIds ResourceIds { get; set; }
#endif
        /// <summary>The status of the webhook.</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_status? Status { get; set; }
        /// <summary>The date the webhook was created at, in ISO_8601 format.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The endpoint that receives events from the webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The unique identifier of the user that created the webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1"/> and sets the default values.
        /// </summary>
        public WebhooksGetResponse_dataMember1()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_status.Enabled;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "deletedAt", n => { DeletedAt = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_deletedAt>(global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_deletedAt.CreateFromDiscriminatorValue); } },
                { "events", n => { Events = n.GetCollectionOfEnumValues<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_events>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "label", n => { Label = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_label>(global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_label.CreateFromDiscriminatorValue); } },
                { "orgId", n => { OrgId = n.GetStringValue(); } },
                { "resourceIds", n => { ResourceIds = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_resourceIds>(global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_resourceIds.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_status>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_deletedAt>("deletedAt", DeletedAt);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_events>("events", Events);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("key", Key);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_label>("label", Label);
            writer.WriteStringValue("orgId", OrgId);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_resourceIds>("resourceIds", ResourceIds);
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_status>("status", Status);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_deletedAtMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WebhooksGetResponse_dataMember1_deletedAt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_deletedAtMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_deletedAtMember1? WebhooksGetResponseDataMember1DeletedAtMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_deletedAtMember1 WebhooksGetResponseDataMember1DeletedAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_deletedAt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_deletedAt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_deletedAt();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.WebhooksGetResponseDataMember1DeletedAtMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_deletedAtMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WebhooksGetResponseDataMember1DeletedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WebhooksGetResponseDataMember1DeletedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_deletedAtMember1>(null, WebhooksGetResponseDataMember1DeletedAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_labelMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WebhooksGetResponse_dataMember1_label : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_labelMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_labelMember1? WebhooksGetResponseDataMember1LabelMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_labelMember1 WebhooksGetResponseDataMember1LabelMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_label"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_label CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_label();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WebhooksGetResponseDataMember1LabelMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_labelMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WebhooksGetResponseDataMember1LabelMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WebhooksGetResponseDataMember1LabelMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1_labelMember1>(null, WebhooksGetResponseDataMember1LabelMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WebhooksGetResponse_dataMember1_resourceIds : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_resourceIds"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_resourceIds CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksGetResponse_dataMember1.WebhooksGetResponse_dataMember1_resourceIds();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
