// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Quo.OpenApiClient.V1.CallRecordings;
using Soenneker.Quo.OpenApiClient.V1.CallSummaries;
using Soenneker.Quo.OpenApiClient.V1.CallTranscripts;
using Soenneker.Quo.OpenApiClient.V1.CallVoicemails;
using Soenneker.Quo.OpenApiClient.V1.Calls;
using Soenneker.Quo.OpenApiClient.V1.ContactCustomFields;
using Soenneker.Quo.OpenApiClient.V1.Contacts;
using Soenneker.Quo.OpenApiClient.V1.Conversations;
using Soenneker.Quo.OpenApiClient.V1.Messages;
using Soenneker.Quo.OpenApiClient.V1.PhoneNumbers;
using Soenneker.Quo.OpenApiClient.V1.Users;
using Soenneker.Quo.OpenApiClient.V1.Webhooks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Quo.OpenApiClient.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The callRecordings property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.CallRecordingsRequestBuilder CallRecordings
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.CallRecordings.CallRecordingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The calls property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Calls.CallsRequestBuilder Calls
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.Calls.CallsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The callSummaries property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.CallSummaries.CallSummariesRequestBuilder CallSummaries
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.CallSummaries.CallSummariesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The callTranscripts property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.CallTranscriptsRequestBuilder CallTranscripts
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.CallTranscripts.CallTranscriptsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The callVoicemails property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.CallVoicemailsRequestBuilder CallVoicemails
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.CallVoicemails.CallVoicemailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contactCustomFields property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.ContactCustomFields.ContactCustomFieldsRequestBuilder ContactCustomFields
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.ContactCustomFields.ContactCustomFieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contacts property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The conversations property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder Conversations
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.Conversations.ConversationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The messages property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Messages.MessagesRequestBuilder Messages
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.Messages.MessagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The phoneNumbers property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.PhoneNumbersRequestBuilder PhoneNumbers
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.PhoneNumbers.PhoneNumbersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Quo.OpenApiClient.V1.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
