// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Quo.OpenApiClient.V1.Contacts.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Contacts
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\contacts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContactsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Quo.OpenApiClient.v1.contacts.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsItemRequestBuilder"/></returns>
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/contacts?maxResults={maxResults}{&externalIds*,pageToken*,sources*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/contacts?maxResults={maxResults}{&externalIds*,pageToken*,sources*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve a paginated list of contacts. You can optionally filter the results by providing external IDs and sources. When no external IDs are provided, all contacts for the organization are returned.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts409Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsGetResponse>(requestInfo, global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a contact for a workspace.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsPostResponse?> PostAsync(global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsPostResponse> PostAsync(global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts409Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Contacts500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsPostResponse>(requestInfo, global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve a paginated list of contacts. You can optionally filter the results by providing external IDs and sources. When no external IDs are provided, all contacts for the organization are returned.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a contact for a workspace.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/v1/contacts", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Quo.OpenApiClient.V1.Contacts.ContactsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve a paginated list of contacts. You can optionally filter the results by providing external IDs and sources. When no external IDs are provided, all contacts for the organization are returned.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("externalIds")]
            public string[]? ExternalIds { get; set; }
#nullable restore
#else
            [QueryParameter("externalIds")]
            public string[] ExternalIds { get; set; }
#endif
            [QueryParameter("maxResults")]
            public int? MaxResults { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pageToken")]
            public string? PageToken { get; set; }
#nullable restore
#else
            [QueryParameter("pageToken")]
            public string PageToken { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sources")]
            public string[]? Sources { get; set; }
#nullable restore
#else
            [QueryParameter("sources")]
            public string[] Sources { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
