// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum A2P10DlcDailyLimitReachedForHelpIncreasingThisLimitCommaVisitHttpsColonSlashSlashSupportQuoComHelpSubmitARequestDescription
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "A2P 10DLC Daily limit reached. For help increasing this limit, visit https://support.quo.com/help/submit-a-request")]
        #pragma warning disable CS1591
        A2P10DLCDailyLimitReachedForHelpIncreasingThisLimitCommaVisitHttpsColonSlashSlashSupportQuoComHelpSubmitARequest,
        #pragma warning restore CS1591
    }
}
