// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateContactV1404_title
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Not Found")]
        #pragma warning disable CS1591
        NotFound,
        #pragma warning restore CS1591
    }
}
