// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateCallTranscriptWebhookV1RequestEventsItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "call.transcript.completed")]
        #pragma warning disable CS1591
        CallTranscriptCompleted,
        #pragma warning restore CS1591
    }
}
