// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetCallVoicemailsV1200ResponseData : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The length of the call voicemail in seconds. Null if the voicemail is not completed or the duration is unknown.</summary>
        public int? Duration { get; set; }
        /// <summary>The unique identifier of the call voicemail.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The URL where the call voicemail can be accessed or downloaded. Null if the voicemail is not completed or the URL is not available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordingUrl { get; set; }
#nullable restore
#else
        public string RecordingUrl { get; set; }
#endif
        /// <summary>The current status of the call voicemail.</summary>
        public global::Soenneker.Quo.OpenApiClient.Models.GetCallVoicemailsV1200ResponseDataStatus? Status { get; set; }
        /// <summary>The transcript of the call voicemail. Null if the voicemail is not completed or the transcript is not available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Transcript { get; set; }
#nullable restore
#else
        public string Transcript { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetCallVoicemailsV1200ResponseData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.Models.GetCallVoicemailsV1200ResponseData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.Models.GetCallVoicemailsV1200ResponseData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "recordingUrl", n => { RecordingUrl = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Quo.OpenApiClient.Models.GetCallVoicemailsV1200ResponseDataStatus>(); } },
                { "transcript", n => { Transcript = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("duration", Duration);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("recordingUrl", RecordingUrl);
            writer.WriteEnumValue<global::Soenneker.Quo.OpenApiClient.Models.GetCallVoicemailsV1200ResponseDataStatus>("status", Status);
            writer.WriteStringValue("transcript", Transcript);
        }
    }
}
#pragma warning restore CS0618
