// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCallByIdV1400_description
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Too Many Participants")]
        #pragma warning disable CS1591
        TooManyParticipants,
        #pragma warning restore CS1591
    }
}
