// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetContactByIdV1200_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp of contact creation in ISO 8601 format.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The unique identifier of the user who created the contact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedByUserId { get; set; }
#nullable restore
#else
        public string CreatedByUserId { get; set; }
#endif
        /// <summary>The customFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_customFields>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_customFields> CustomFields { get; set; }
#endif
        /// <summary>The defaultFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_defaultFields? DefaultFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_defaultFields DefaultFields { get; set; }
#endif
        /// <summary>A unique identifier from an external system that can optionally be supplied when creating a contact. This ID is used to associate the contact with records in other systems and is required for retrieving the contact later via the &quot;List Contacts&quot; endpoint. Ensure the `externalId` is unique and consistent across systems for accurate cross-referencing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>The unique identifier of the contact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Indicates how the contact was created or where it originated from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>A link to the contact in the source system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceUrl { get; set; }
#nullable restore
#else
        public string SourceUrl { get; set; }
#endif
        /// <summary>Timestamp of last contact update in ISO 8601 format.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data"/> and sets the default values.
        /// </summary>
        public GetContactByIdV1200_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdByUserId", n => { CreatedByUserId = n.GetStringValue(); } },
                { "customFields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_customFields>(global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_customFields.CreateFromDiscriminatorValue)?.AsList(); } },
                { "defaultFields", n => { DefaultFields = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_defaultFields>(global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_defaultFields.CreateFromDiscriminatorValue); } },
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "sourceUrl", n => { SourceUrl = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdByUserId", CreatedByUserId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_customFields>("customFields", CustomFields);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.GetContactByIdV1200_data_defaultFields>("defaultFields", DefaultFields);
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("sourceUrl", SourceUrl);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
