// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCallRecordingsV1400_code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "0900400")]
        #pragma warning disable CS1591
        ZeroNineZeroZeroFourZeroZero,
        #pragma warning restore CS1591
    }
}
