// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCallVoicemailsV1404_code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "1200404")]
        #pragma warning disable CS1591
        OneTwoZeroZeroFourZeroFour,
        #pragma warning restore CS1591
    }
}
