// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetMessageByIdV1402_title
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Subscription Expired")]
        #pragma warning disable CS1591
        SubscriptionExpired,
        #pragma warning restore CS1591
    }
}
