// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetMessageByIdV1402Response_code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "0201402")]
        #pragma warning disable CS1591
        Value0201402,
        #pragma warning restore CS1591
    }
}
