// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetWebhookByIdV1200_dataMember5_resourceIds
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "*")]
        #pragma warning disable CS1591
        Asterisk,
        #pragma warning restore CS1591
    }
}
