// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetWebhookByIdV1200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200.GetWebhookByIdV1200_data? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200.GetWebhookByIdV1200_data Data { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200"/> and sets the default values.
        /// </summary>
        public GetWebhookByIdV1200()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200.GetWebhookByIdV1200_data>(global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200.GetWebhookByIdV1200_data.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200.GetWebhookByIdV1200_data>("data", Data);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember1"/>, <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember2"/>, <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember3"/>, <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember4"/>, <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember5"/>, <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember6"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetWebhookByIdV1200_data : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember1? GetWebhookByIdV1200DataMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember1 GetWebhookByIdV1200DataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember2? GetWebhookByIdV1200DataMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember2 GetWebhookByIdV1200DataMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember3? GetWebhookByIdV1200DataMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember3 GetWebhookByIdV1200DataMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember4? GetWebhookByIdV1200DataMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember4 GetWebhookByIdV1200DataMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember5? GetWebhookByIdV1200DataMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember5 GetWebhookByIdV1200DataMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember6? GetWebhookByIdV1200DataMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember6 GetWebhookByIdV1200DataMember6 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200.GetWebhookByIdV1200_data"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200.GetWebhookByIdV1200_data CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200.GetWebhookByIdV1200_data();
                result.GetWebhookByIdV1200DataMember1 = new global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember1();
                result.GetWebhookByIdV1200DataMember2 = new global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember2();
                result.GetWebhookByIdV1200DataMember3 = new global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember3();
                result.GetWebhookByIdV1200DataMember4 = new global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember4();
                result.GetWebhookByIdV1200DataMember5 = new global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember5();
                result.GetWebhookByIdV1200DataMember6 = new global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember6();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GetWebhookByIdV1200DataMember1 != null || GetWebhookByIdV1200DataMember2 != null || GetWebhookByIdV1200DataMember3 != null || GetWebhookByIdV1200DataMember4 != null || GetWebhookByIdV1200DataMember5 != null || GetWebhookByIdV1200DataMember6 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GetWebhookByIdV1200DataMember1, GetWebhookByIdV1200DataMember2, GetWebhookByIdV1200DataMember3, GetWebhookByIdV1200DataMember4, GetWebhookByIdV1200DataMember5, GetWebhookByIdV1200DataMember6);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.GetWebhookByIdV1200_dataMember1>(null, GetWebhookByIdV1200DataMember1, GetWebhookByIdV1200DataMember2, GetWebhookByIdV1200DataMember3, GetWebhookByIdV1200DataMember4, GetWebhookByIdV1200DataMember5, GetWebhookByIdV1200DataMember6);
            }
        }
    }
}
#pragma warning restore CS0618
