// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListPhoneNumbersResponseDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp of when the phone number was added to the account in ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>A human-readable representation of a phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormattedNumber { get; set; }
#nullable restore
#else
        public string FormattedNumber { get; set; }
#endif
        /// <summary>Forwarding number for incoming calls, null if no forwarding number is configured.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Forward { get; set; }
#nullable restore
#else
        public string Forward { get; set; }
#endif
        /// <summary>The unique identifier of the group to which the Quo number belongs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The unique identifier of Quo phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The display name of the phone number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A phone number in E.164 format, including the country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>Current status of the porting process, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PortingStatus { get; set; }
#nullable restore
#else
        public string PortingStatus { get; set; }
#endif
        /// <summary>Unique identifier for the phone number’s porting request, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PortRequestId { get; set; }
#nullable restore
#else
        public string PortRequestId { get; set; }
#endif
        /// <summary>The restrictions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemRestrictions? Restrictions { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemRestrictions Restrictions { get; set; }
#endif
        /// <summary>Custom symbol or emoji associated with the phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Symbol { get; set; }
#nullable restore
#else
        public string Symbol { get; set; }
#endif
        /// <summary>Timestamp of the last update to the phone number&apos;s details in ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The users property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemUsersItem>? Users { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemUsersItem> Users { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItem"/> and sets the default values.
        /// </summary>
        public ListPhoneNumbersResponseDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "formattedNumber", n => { FormattedNumber = n.GetStringValue(); } },
                { "forward", n => { Forward = n.GetStringValue(); } },
                { "groupId", n => { GroupId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "portRequestId", n => { PortRequestId = n.GetStringValue(); } },
                { "portingStatus", n => { PortingStatus = n.GetStringValue(); } },
                { "restrictions", n => { Restrictions = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemRestrictions>(global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemRestrictions.CreateFromDiscriminatorValue); } },
                { "symbol", n => { Symbol = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
                { "users", n => { Users = n.GetCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemUsersItem>(global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemUsersItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteStringValue("formattedNumber", FormattedNumber);
            writer.WriteStringValue("forward", Forward);
            writer.WriteStringValue("groupId", GroupId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("number", Number);
            writer.WriteStringValue("portingStatus", PortingStatus);
            writer.WriteStringValue("portRequestId", PortRequestId);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemRestrictions>("restrictions", Restrictions);
            writer.WriteStringValue("symbol", Symbol);
            writer.WriteStringValue("updatedAt", UpdatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponseDataItemUsersItem>("users", Users);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
