// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListContactsV1400Response_description
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Invalid Custom Field Item")]
        #pragma warning disable CS1591
        InvalidCustomFieldItem,
        #pragma warning restore CS1591
    }
}
