// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListContactsV1200ResponseDataItemDefaultFields : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contact&apos;s company name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Company { get; set; }
#nullable restore
#else
        public string Company { get; set; }
#endif
        /// <summary>The emails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsEmailsItem>? Emails { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsEmailsItem> Emails { get; set; }
#endif
        /// <summary>The contact&apos;s first name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The contact&apos;s last name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The phoneNumbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsPhoneNumbersItem>? PhoneNumbers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsPhoneNumbersItem> PhoneNumbers { get; set; }
#endif
        /// <summary>The contact&apos;s role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFields"/> and sets the default values.
        /// </summary>
        public ListContactsV1200ResponseDataItemDefaultFields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "company", n => { Company = n.GetStringValue(); } },
                { "emails", n => { Emails = n.GetCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsEmailsItem>(global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsEmailsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "phoneNumbers", n => { PhoneNumbers = n.GetCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsPhoneNumbersItem>(global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsPhoneNumbersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "role", n => { Role = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("company", Company);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsEmailsItem>("emails", Emails);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.ListContactsV1200ResponseDataItemDefaultFieldsPhoneNumbersItem>("phoneNumbers", PhoneNumbers);
            writer.WriteStringValue("role", Role);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
