// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListPhoneNumbersResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp of when the phone number was added to the account in ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The formattedNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_formattedNumber? FormattedNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_formattedNumber FormattedNumber { get; set; }
#endif
        /// <summary>The forward property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_forward? Forward { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_forward Forward { get; set; }
#endif
        /// <summary>The unique identifier of the group to which the OpenPhone number belongs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The unique identifier of OpenPhone phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The display name of the phone number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A phone number in E.164 format, including the country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The portingStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portingStatus? PortingStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portingStatus PortingStatus { get; set; }
#endif
        /// <summary>The portRequestId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portRequestId? PortRequestId { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portRequestId PortRequestId { get; set; }
#endif
        /// <summary>The restrictions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_restrictions? Restrictions { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_restrictions Restrictions { get; set; }
#endif
        /// <summary>The symbol property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_symbol? Symbol { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_symbol Symbol { get; set; }
#endif
        /// <summary>Timestamp of the last update to the phone number&apos;s details in ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The users property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_users>? Users { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_users> Users { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data"/> and sets the default values.
        /// </summary>
        public ListPhoneNumbersResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "formattedNumber", n => { FormattedNumber = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_formattedNumber>(global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_formattedNumber.CreateFromDiscriminatorValue); } },
                { "forward", n => { Forward = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_forward>(global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_forward.CreateFromDiscriminatorValue); } },
                { "groupId", n => { GroupId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "portRequestId", n => { PortRequestId = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portRequestId>(global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portRequestId.CreateFromDiscriminatorValue); } },
                { "portingStatus", n => { PortingStatus = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portingStatus>(global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portingStatus.CreateFromDiscriminatorValue); } },
                { "restrictions", n => { Restrictions = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_restrictions>(global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_restrictions.CreateFromDiscriminatorValue); } },
                { "symbol", n => { Symbol = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_symbol>(global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_symbol.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
                { "users", n => { Users = n.GetCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_users>(global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_users.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_formattedNumber>("formattedNumber", FormattedNumber);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_forward>("forward", Forward);
            writer.WriteStringValue("groupId", GroupId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("number", Number);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portingStatus>("portingStatus", PortingStatus);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portRequestId>("portRequestId", PortRequestId);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_restrictions>("restrictions", Restrictions);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_symbol>("symbol", Symbol);
            writer.WriteStringValue("updatedAt", UpdatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_users>("users", Users);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_formattedNumberMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListPhoneNumbersResponse_data_formattedNumber : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_formattedNumberMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_formattedNumberMember1? ListPhoneNumbersResponseDataFormattedNumberMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_formattedNumberMember1 ListPhoneNumbersResponseDataFormattedNumberMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_formattedNumber"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_formattedNumber CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_formattedNumber();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ListPhoneNumbersResponseDataFormattedNumberMember1 = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_formattedNumberMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ListPhoneNumbersResponseDataFormattedNumberMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ListPhoneNumbersResponseDataFormattedNumberMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_formattedNumberMember1>(null, ListPhoneNumbersResponseDataFormattedNumberMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_forwardMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListPhoneNumbersResponse_data_forward : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_forwardMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_forwardMember1? ListPhoneNumbersResponseDataForwardMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_forwardMember1 ListPhoneNumbersResponseDataForwardMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_forward"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_forward CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_forward();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ListPhoneNumbersResponseDataForwardMember1 = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_forwardMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ListPhoneNumbersResponseDataForwardMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ListPhoneNumbersResponseDataForwardMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_forwardMember1>(null, ListPhoneNumbersResponseDataForwardMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portingStatusMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListPhoneNumbersResponse_data_portingStatus : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portingStatusMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portingStatusMember1? ListPhoneNumbersResponseDataPortingStatusMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portingStatusMember1 ListPhoneNumbersResponseDataPortingStatusMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portingStatus"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portingStatus CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portingStatus();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ListPhoneNumbersResponseDataPortingStatusMember1 = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portingStatusMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ListPhoneNumbersResponseDataPortingStatusMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ListPhoneNumbersResponseDataPortingStatusMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portingStatusMember1>(null, ListPhoneNumbersResponseDataPortingStatusMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portRequestIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListPhoneNumbersResponse_data_portRequestId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portRequestIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portRequestIdMember1? ListPhoneNumbersResponseDataPortRequestIdMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portRequestIdMember1 ListPhoneNumbersResponseDataPortRequestIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portRequestId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portRequestId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_portRequestId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ListPhoneNumbersResponseDataPortRequestIdMember1 = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portRequestIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ListPhoneNumbersResponseDataPortRequestIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ListPhoneNumbersResponseDataPortRequestIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_portRequestIdMember1>(null, ListPhoneNumbersResponseDataPortRequestIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_symbolMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListPhoneNumbersResponse_data_symbol : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_symbolMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_symbolMember1? ListPhoneNumbersResponseDataSymbolMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_symbolMember1 ListPhoneNumbersResponseDataSymbolMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_symbol"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_symbol CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data.ListPhoneNumbersResponse_data_symbol();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ListPhoneNumbersResponseDataSymbolMember1 = new global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_symbolMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ListPhoneNumbersResponseDataSymbolMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ListPhoneNumbersResponseDataSymbolMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.Models.ListPhoneNumbersResponse_data_symbolMember1>(null, ListPhoneNumbersResponseDataSymbolMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
