// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SendMessageV1500_code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "0201500")]
        #pragma warning disable CS1591
        ZeroTwoZeroOneFiveZeroZero,
        #pragma warning restore CS1591
    }
}
