// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateTaskV1404Response_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "404")]
        #pragma warning disable CS1591
        Value404,
        #pragma warning restore CS1591
    }
}
