// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Quo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Value0204403Code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "0204403")]
        #pragma warning disable CS1591
        Value0204403,
        #pragma warning restore CS1591
    }
}
