// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Contacts.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ContactsPatchResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp of contact creation in ISO 8601 format.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The unique identifier of the user who created the contact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedByUserId { get; set; }
#nullable restore
#else
        public string CreatedByUserId { get; set; }
#endif
        /// <summary>The customFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_customFields>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_customFields> CustomFields { get; set; }
#endif
        /// <summary>The defaultFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_defaultFields? DefaultFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_defaultFields DefaultFields { get; set; }
#endif
        /// <summary>The externalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_externalId? ExternalId { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_externalId ExternalId { get; set; }
#endif
        /// <summary>The unique identifier of the contact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_source? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_source Source { get; set; }
#endif
        /// <summary>The sourceUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_sourceUrl? SourceUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_sourceUrl SourceUrl { get; set; }
#endif
        /// <summary>Timestamp of last contact update in ISO 8601 format.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data"/> and sets the default values.
        /// </summary>
        public ContactsPatchResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdByUserId", n => { CreatedByUserId = n.GetStringValue(); } },
                { "customFields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_customFields>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_customFields.CreateFromDiscriminatorValue)?.AsList(); } },
                { "defaultFields", n => { DefaultFields = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_defaultFields>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_defaultFields.CreateFromDiscriminatorValue); } },
                { "externalId", n => { ExternalId = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_externalId>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_externalId.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_source>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_source.CreateFromDiscriminatorValue); } },
                { "sourceUrl", n => { SourceUrl = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_sourceUrl>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_sourceUrl.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdByUserId", CreatedByUserId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_customFields>("customFields", CustomFields);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_defaultFields>("defaultFields", DefaultFields);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_externalId>("externalId", ExternalId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_source>("source", Source);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_sourceUrl>("sourceUrl", SourceUrl);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_externalIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsPatchResponse_data_externalId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_externalIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_externalIdMember1? ContactsPatchResponseDataExternalIdMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_externalIdMember1 ContactsPatchResponseDataExternalIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_externalId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_externalId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_externalId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ContactsPatchResponseDataExternalIdMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_externalIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ContactsPatchResponseDataExternalIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ContactsPatchResponseDataExternalIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_externalIdMember1>(null, ContactsPatchResponseDataExternalIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsPatchResponse_data_source : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceMember1? ContactsPatchResponseDataSourceMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceMember1 ContactsPatchResponseDataSourceMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_source"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_source CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_source();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ContactsPatchResponseDataSourceMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ContactsPatchResponseDataSourceMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ContactsPatchResponseDataSourceMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceMember1>(null, ContactsPatchResponseDataSourceMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceUrlMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsPatchResponse_data_sourceUrl : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceUrlMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceUrlMember1? ContactsPatchResponseDataSourceUrlMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceUrlMember1 ContactsPatchResponseDataSourceUrlMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_sourceUrl"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_sourceUrl CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data.ContactsPatchResponse_data_sourceUrl();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ContactsPatchResponseDataSourceUrlMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceUrlMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ContactsPatchResponseDataSourceUrlMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ContactsPatchResponseDataSourceUrlMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse_data_sourceUrlMember1>(null, ContactsPatchResponseDataSourceUrlMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
