// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Contacts.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ContactsPatchRequestBody_defaultFields : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_company? Company { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_company Company { get; set; }
#endif
        /// <summary>The emails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_emails>? Emails { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_emails> Emails { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_firstName? FirstName { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_firstName FirstName { get; set; }
#endif
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_lastName? LastName { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_lastName LastName { get; set; }
#endif
        /// <summary>The phoneNumbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_phoneNumbers>? PhoneNumbers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_phoneNumbers> PhoneNumbers { get; set; }
#endif
        /// <summary>The role property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_role? Role { get; set; }
#nullable restore
#else
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_role Role { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields"/> and sets the default values.
        /// </summary>
        public ContactsPatchRequestBody_defaultFields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "company", n => { Company = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_company>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_company.CreateFromDiscriminatorValue); } },
                { "emails", n => { Emails = n.GetCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_emails>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_emails.CreateFromDiscriminatorValue)?.AsList(); } },
                { "firstName", n => { FirstName = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_firstName>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_firstName.CreateFromDiscriminatorValue); } },
                { "lastName", n => { LastName = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_lastName>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_lastName.CreateFromDiscriminatorValue); } },
                { "phoneNumbers", n => { PhoneNumbers = n.GetCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_phoneNumbers>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_phoneNumbers.CreateFromDiscriminatorValue)?.AsList(); } },
                { "role", n => { Role = n.GetObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_role>(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_role.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_company>("company", Company);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_emails>("emails", Emails);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_firstName>("firstName", FirstName);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_lastName>("lastName", LastName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_phoneNumbers>("phoneNumbers", PhoneNumbers);
            writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_role>("role", Role);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_companyMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsPatchRequestBody_defaultFields_company : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_companyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_companyMember1? ContactsPatchRequestBodyDefaultFieldsCompanyMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_companyMember1 ContactsPatchRequestBodyDefaultFieldsCompanyMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_company"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_company CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_company();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ContactsPatchRequestBodyDefaultFieldsCompanyMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_companyMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ContactsPatchRequestBodyDefaultFieldsCompanyMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ContactsPatchRequestBodyDefaultFieldsCompanyMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_companyMember1>(null, ContactsPatchRequestBodyDefaultFieldsCompanyMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_firstNameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsPatchRequestBody_defaultFields_firstName : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_firstNameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_firstNameMember1? ContactsPatchRequestBodyDefaultFieldsFirstNameMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_firstNameMember1 ContactsPatchRequestBodyDefaultFieldsFirstNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_firstName"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_firstName CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_firstName();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ContactsPatchRequestBodyDefaultFieldsFirstNameMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_firstNameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ContactsPatchRequestBodyDefaultFieldsFirstNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ContactsPatchRequestBodyDefaultFieldsFirstNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_firstNameMember1>(null, ContactsPatchRequestBodyDefaultFieldsFirstNameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_lastNameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsPatchRequestBody_defaultFields_lastName : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_lastNameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_lastNameMember1? ContactsPatchRequestBodyDefaultFieldsLastNameMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_lastNameMember1 ContactsPatchRequestBodyDefaultFieldsLastNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_lastName"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_lastName CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_lastName();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ContactsPatchRequestBodyDefaultFieldsLastNameMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_lastNameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ContactsPatchRequestBodyDefaultFieldsLastNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ContactsPatchRequestBodyDefaultFieldsLastNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_lastNameMember1>(null, ContactsPatchRequestBodyDefaultFieldsLastNameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_roleMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsPatchRequestBody_defaultFields_role : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_roleMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_roleMember1? ContactsPatchRequestBodyDefaultFieldsRoleMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_roleMember1 ContactsPatchRequestBodyDefaultFieldsRoleMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_role"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_role CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields.ContactsPatchRequestBody_defaultFields_role();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ContactsPatchRequestBodyDefaultFieldsRoleMember1 = new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_roleMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ContactsPatchRequestBodyDefaultFieldsRoleMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ContactsPatchRequestBodyDefaultFieldsRoleMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody_defaultFields_roleMember1>(null, ContactsPatchRequestBodyDefaultFieldsRoleMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
