// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Quo.OpenApiClient.V1.Contacts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\contacts\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContactsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/contacts/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/contacts/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a contact by its unique identifier.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve detailed information about a specific contact in your OpenPhone workspace using the contact&apos;s unique identifier.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsGetResponse?> GetAsContactsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsGetResponse> GetAsContactsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsGetResponse>(requestInfo, global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve detailed information about a specific contact in your OpenPhone workspace using the contact&apos;s unique identifier.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsContactsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse>(requestInfo, global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Modify an existing contact in your OpenPhone workspace using the contact&apos;s unique identifier.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse?> PatchAsContactsPatchResponseAsync(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse> PatchAsContactsPatchResponseAsync(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse>(requestInfo, global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Modify an existing contact in your OpenPhone workspace using the contact&apos;s unique identifier.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PatchAsContactsPatchResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse?> PatchAsync(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse> PatchAsync(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts409Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.Contacts500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse>(requestInfo, global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a contact by its unique identifier.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieve detailed information about a specific contact in your OpenPhone workspace using the contact&apos;s unique identifier.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Modify an existing contact in your OpenPhone workspace using the contact&apos;s unique identifier.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Quo.OpenApiClient.V1.Contacts.Item.ContactsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsItemRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
